### ISSUE TITLE
Nodes do not get removed and connected properly

### ISSUE THREAD

**Issue by Klausstaler** [Klausstaler/sdp-21#31]
1. In the lower right, I tried connecting to yellow nodes. Instead of drawing a line between them, it has drawn a line between the first yellow node and some unassigned node.
2. When connecting two red nodes in the lower right, it did not delete the nodes in between.
![image](https://user-images.githubusercontent.com/41381124/112621161-54a38680-8e21-11eb-9bb5-78fc2d644a56.png)

**Comment by ryan75195** [comment]
try latest push and see if its fixed
