### ISSUE TITLE
RFID tags do not get correctly generated when using the Frontend

### ISSUE THREAD

**Issue by Klausstaler** [Klausstaler/sdp-21#32]
When generating a warehouse, sometimes RFID tags do not get placed in the simulation even though they should.

In the warehouse config below, the first, third, fifth and sixth RFID tag (indexing starts at the top left, row-wise) does not get generated.

![image](https://user-images.githubusercontent.com/41381124/112666203-d44a4900-8e53-11eb-8b2d-2f2c6596eb97.png)

**Comment by ryan75195** [comment]
fixed
